### PR TITLE
fix(codesign): use empty CODE_SIGN_IDENTITY

### PR DESCRIPTION
**Pull request by opichals**
This makes Catalina 10.15.5's Mail.app 13.4 stop complaining about compatibility.

### CODE REVIEW

**Comment by NemoLi72** [comment]
#1 how to use? I'm newbie...

**Comment by wwwjfy** [comment]
Sorry I didn't set up the notifications correctly so I didn't see this.

@opichals I don't get why CODE_SIGN_IDENTITY is related to compatibility. For the linked issues, they don't have the `Supported10.15PluginCompatibilityUUIDs` in Info.plist but it's not the case here.

**Comment by opichals** [comment]
@wwwjfy I am not sure either but when I drop this it stops working. :)

**Comment by wwwjfy** [comment]
I suspect it's because you're using the local build. Have you tried local build without this?

How Mac works is a mystery, at least to me. I don't quite remember now but I suffered some issues when I first came to 10.15, so I forked the repo and fixed it to make it work for me.

I'm now thinking it might be actually code signing issue that if others have similar issues I could sign with my own signature.

**Comment by opichals** [comment]
> I suspect it's because you're using the local build. Have you tried local build without this?

Confused about what you mean here. There are no binaries so yes, I was building it locally.

**Comment by wwwjfy** [comment]
There is a binary, just in the form of .mailbundle not usual .app (Strictly, ~/Library/Mail/Bundles/GMailinator.mailbundle/Contents/MacOS/GMailinator)

Let me see if I can reproduce it and why this can happen.

**Comment by opichals** [comment]
Ah, there are binaries in the github releases section.

I have been trying to avoid using pre-built binaries as much as possible for privacy reasons.

**Comment by wwwjfy** [comment]
I see.

Still not sure. I've seen some issues related to Catalina's DataVaults feature.

If not too much trouble, could you try to use the problematic version with Console open and filter logs by `GMailinator`. It should give the reason why it fails.
It seems the UUID compatibility error is just a generic one, regardless of the actual reason.

**Comment by wwwjfy** [comment]
I can reproduce and fix it with unrelated changes like empty lines. So I don't think this code sign setting is related. Clean and rebuild might fix it.

**Comment by opichals** [comment]
Interesting, thanks for investigating.

**Pull request closed without merging**
